### ISSUE TITLE
temporary files older than 5 days must be deleted

### ISSUE THREAD

**Issue by cristiroma** [eaudeweb/meetings-registration-tool#46]
FOLDERS
* /printouts/
* / .... 

CORNEL TO COMPLETE

**Comment by cristiroma** [comment]
Create a cron script  once a day

``
find /path/to/files* -mtime +5 -exec rm {} \;
``

**Comment by nico4** [comment]
I documented the following command in the README file; can be triggered as a cron job.

> docker exec mrt.rq python manage.py rq cleanup --hook clean_printouts
